/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fruteria;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JUAN E
 */
public class EditarFrutas extends javax.swing.JFrame {

    /**
     * Creates new form EditarFrutas
     */
    private DefaultTableModel model;
    private int row;
    private final JTable jTableProducto;
    private final CarritoFruta aThis;
    
    public EditarFrutas(String nombre, int cantidad, double precio, DefaultTableModel modelo, int row, JTable jTableProducto, CarritoFruta aThis) {
        initComponents();
        this.NombreFruta.setText(nombre);
        this.CantidadFruta.setText(cantidad+"");
        this.PrecioFruta.setText(precio+"");
        this.model=modelo;
        this.row=row;
        this.jTableProducto=jTableProducto;
        this.aThis=aThis;           
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NombreFruta = new javax.swing.JTextField();
        CantidadFruta = new javax.swing.JTextField();
        PrecioFruta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NOMBRE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 43, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CANTIDAD");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 43, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PRECIO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        NombreFruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreFrutaActionPerformed(evt);
            }
        });
        jPanel1.add(NombreFruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 77, 70, -1));
        jPanel1.add(CantidadFruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 77, 70, -1));
        jPanel1.add(PrecioFruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 70, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("EDITAR PRODUCTO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 250, -1, -1));

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 250, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FruImagenes/fondofrutitas_1.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 410, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CarritoFruta a= new CarritoFruta();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
                String nombre =  this.NombreFruta.getText();
                String cantidad =  this.CantidadFruta.getText();
                String precio =  this.PrecioFruta.getText();
                
                if(!nombre.isEmpty() && !cantidad.isEmpty() && !precio.isEmpty()){
                     int c = Integer.parseInt( cantidad);
                     double p = Double.parseDouble( precio);
                     if(c>0 && p>0)
                     {
                         this.model.setValueAt(nombre, row, 0);
                         this.model.setValueAt(cantidad, row, 1);
                         this.model.setValueAt(precio, row, 2);
                         this.jTableProducto.repaint();
                         this.aThis.show();
                         this.dispose();
                     }
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NombreFrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreFrutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreFrutaActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CantidadFruta;
    private javax.swing.JTextField NombreFruta;
    private javax.swing.JTextField PrecioFruta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
